const array = [
    {city:'Bangalore',
    state:'Karnataka',
    degree :26,
    weather:'Partly Cloudy',
    image:'images/cloudy.svg'},
    {city:'Chennai',
    state:'TamilNadu',
    degree :34,
    weather:'Sunny',
    image:'images/sunny.svg'},
    {city:'Coimbatore',
    state:'TamilNadu',
    degree :26,
    weather:'Partly Cloudy',
    image:'images/cloudy.svg'},
    {city:'Noida',
    state:'Delhi',
    degree :23,
    weather:'Thunder',
    image:'images/thunder.svg'},
    {city:'Patna',
    state:'Bihar',
    degree :30,
    weather:'Humidity',
    image:'image/humid.svg'},
    {city:'Gurugram',
    state:'Haryana',
    degree :34,
    weather:'Sunny',
    image:'images/sunny.svg'},
    {city:'Mumbai',
    state:'Maharashtra',
    degree :20,
    weather:'Rainy',
    image:'images/rainy.svg'},
    {city:'Amaravati',
    state:'Andra Pradesh',
    degree :23,
    weather:'Humidity',
    image:'image/humid.svg'},
    {city:'Jaipur',
    state:'Rajasthan',
    degree :32,
    weather:'Sunny',
    image:'images/sunny.svg'},
    {city:'Panaji',
    state:'Goa',
    degree :22,
    weather:'Rainy',
    image:'images/rainy.svg'},
    {city:'Mysore',
    state:'Karnataka',
    degree :24,
    weather:'Partly Cloudy',
    image:'images/cloudy.svg'},
    {city:'Madurai',
    state:'TamilNadu',
    degree :35,
    weather:'Sunny',
    image:'images/sunny.svg'},
    {city:'Alleppey',
    state:'Kerala',
    degree :20,
    weather:'Rainy',
    image:'images/rainy.svg'}   
];
